version: '3.8'

services:
  db:
    build: ./db
    env_file:
      - ./.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local

  app:
    build: ./
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

    networks:
      - local 


networks:
  local:

volumes:
  db-data:
